### ISSUE TITLE
Walls not spawning properly.

### ISSUE THREAD

**Issue by BradFitz66** [alexismorin/floorplan#1]
I installed the plugin via git clone (maybe I should have done via package?) and tried it out only to realize that the walls don't align with the handle properly.

All I've done is:
1. Install
2. Create handle
3. Set create walls to true from inspector
4. Press space
5. Hold control while moving the handle

I'm using Unity 2018.3.2f1 and no errors appear in the console while moving handle.

Here's a screenshot  of what I see:
![Hh3jHBj](https://user-images.githubusercontent.com/28825575/56308521-63fefd00-613f-11e9-97d5-a2e4336393ce.png)

**Comment by alexismorin** [comment]
The Editor-side API has always been a little wonky;  It seems to do what you're describing only in versions older than 2019.1 - I guess for now it's a limitation I can't seem to wrap my head around! I'll add a bit about in the readme.

**Comment by badf** [comment]
Update: I have solved the issue.

The issue was with the tileset that comes with the plugin and not with anything code-side. Two of the prefabs (walls and pillars) are offset from their parent in the prefab itself. If you have this issue, open the pillar and wall prefab and set the actual model of the prefab, which is a child of an empty, to 0,0,0.

**Comment by BradFitz66** [comment]
Update: I have solved the issue.

The issue was with the tileset that comes with the plugin and not with anything code-side. Two of the prefabs (walls and pillars) are offset from their parent in the prefab itself. If you have this issue, open the pillar and wall prefab and set the actual model of the prefab, which is a child of an empty, to 0,0,0.
